apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress
spec:
  defaultBackend:
    service:
      name: {{ .Chart.Name }}-service
      port:
        number: {{ .Values.service.port }}
  ingressClassName: nginx
  rules:
    - host: myapp.local
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: {{ .Chart.Name }}-service
                port:
                  number: {{ .Values.service.port }}
            path: /
