apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
spec:
  ports:
    - name: http-web
      port: {{ .Values.service.port }}
      protocol: TCP
      #targetPort: 8080
      nodePort: 30090
  selector:
    app: {{ .Chart.Name }}
  type: NodePort
  #type: LoadBalancer