apiVersion: skaffold/v2beta10
kind: Config
build:
  artifacts:
    - image: skaffold-demo
      jib: {}

deploy:
  helm:
    releases:
      - name: myapp
        chartPath: ./myapp-chart
        valuesFiles:
          - ./myapp-chart/values.yaml